repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version.
    rev: v0.6.7
    hooks:
      # Run the linter.
      - id: ruff
        types_or: [python, pyi]
        args: [--fix, --exit-non-zero-on-fix]
      # Run the formatter.
      - id: ruff-format
        types_or: [python, pyi]
  - repo: https://github.com/astral-sh/uv-pre-commit
    # uv version.
    rev: 0.4.15
    hooks:
      # Update the uv lockfile
      - id: uv-lock
      - id: uv-export
  - repo: https://github.com/psf/black
    rev: 22.10.0
    hooks:
      - id: black
  - repo: https://github.com/google/yamlfmt
    rev: v0.10.0
    hooks:
      - id: yamlfmt
